"""SQLite-backed archivist annotation store.

Stores free-text notes that archivists attach to documents.  Notes surface
in the retrieval layer as ``ARCHIVIST NOTE:`` lines in the synthesis context,
treated as authoritative by the synthesis engine.

Each document holds at most one *current* note (``is_current = 1``).  Prior
notes are retained for audit history (``is_current = 0``).  The store is
intentionally separate from the review system's ReviewStore: annotations are
proactive knowledge added by archivists, not reactive proposals generated by
detectors.
"""
from __future__ import annotations

import logging
import sqlite3
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_log = logging.getLogger(__name__)

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS document_annotation (
    note_id    TEXT    NOT NULL PRIMARY KEY,
    doc_id     TEXT    NOT NULL,
    note_text  TEXT    NOT NULL,
    created_by TEXT    NOT NULL DEFAULT '',
    created_at TEXT    NOT NULL,
    is_current INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_doc_annotation_current
    ON document_annotation (doc_id, is_current);
"""

_MAX_NOTE_LENGTH = 2000


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _row_to_dict(row: sqlite3.Row) -> dict[str, Any]:
    return dict(row)


class AnnotationStore:
    """SQLite store for archivist document annotations.

    Thread safety: uses ``check_same_thread=False`` with WAL journal mode,
    matching the pattern used by ``ReviewStore``.  Writes are infrequent
    (occasional archivist saves), so SQLite's serialised write lock is adequate.
    """

    def __init__(self, db_path: str | Path, *, conn: sqlite3.Connection | None = None) -> None:
        self.db_path = Path(db_path)
        if conn is not None:
            self._conn = conn
            return
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(str(self.db_path), check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.execute("PRAGMA foreign_keys=ON")
        self._conn.executescript(_SCHEMA_SQL)
        self._conn.commit()
        _log.debug("AnnotationStore opened: %s", self.db_path)

    # ------------------------------------------------------------------
    # Writes
    # ------------------------------------------------------------------

    def upsert_note(self, doc_id: str, note_text: str, created_by: str) -> str:
        """Save a new note for *doc_id*, archiving any previous note.

        Returns the ``note_id`` of the newly created row.
        Raises ``ValueError`` if *note_text* is empty or exceeds the
        character limit.
        """
        stripped = note_text.strip()
        if not stripped:
            raise ValueError("note_text must not be empty")
        if len(stripped) > _MAX_NOTE_LENGTH:
            raise ValueError(
                f"note_text exceeds maximum length of {_MAX_NOTE_LENGTH} characters"
            )

        note_id = str(uuid.uuid4())
        now = _now_iso()

        with self._conn:
            self._conn.execute(
                "UPDATE document_annotation SET is_current = 0"
                " WHERE doc_id = ? AND is_current = 1",
                (doc_id,),
            )
            self._conn.execute(
                "INSERT INTO document_annotation"
                " (note_id, doc_id, note_text, created_by, created_at, is_current)"
                " VALUES (?, ?, ?, ?, ?, 1)",
                (note_id, doc_id, stripped, created_by, now),
            )

        _log.info("AnnotationStore.upsert_note: doc_id=%s note_id=%s", doc_id, note_id)
        return note_id

    # ------------------------------------------------------------------
    # Reads
    # ------------------------------------------------------------------

    def get_current_note(self, doc_id: str) -> dict[str, Any] | None:
        """Return the current note for *doc_id*, or ``None`` if none exists."""
        row = self._conn.execute(
            "SELECT * FROM document_annotation WHERE doc_id = ? AND is_current = 1",
            (doc_id,),
        ).fetchone()
        return _row_to_dict(row) if row is not None else None

    def get_notes_for_docs(self, doc_ids: list[str]) -> dict[str, dict[str, Any]]:
        """Batch-fetch current notes for a list of *doc_ids*.

        Returns ``{doc_id: note_dict}`` for all docs that have a current note.
        Returns an empty dict if *doc_ids* is empty.

        Note: SQLite's default variable limit is 999.  The context window
        budget caps the number of provenance blocks (max ~20), so no chunking
        is needed for the June scope.
        """
        if not doc_ids:
            return {}
        placeholders = ",".join("?" * len(doc_ids))
        rows = self._conn.execute(
            f"SELECT * FROM document_annotation"
            f" WHERE doc_id IN ({placeholders}) AND is_current = 1",
            doc_ids,
        ).fetchall()
        return {row["doc_id"]: _row_to_dict(row) for row in rows}

    def get_note_history(self, doc_id: str, limit: int = 5) -> list[dict[str, Any]]:
        """Return the annotation history for *doc_id*, newest first.

        Includes the current note as well as archived ones.
        """
        rows = self._conn.execute(
            "SELECT * FROM document_annotation"
            " WHERE doc_id = ?"
            " ORDER BY created_at DESC"
            " LIMIT ?",
            (doc_id, limit),
        ).fetchall()
        return [_row_to_dict(r) for r in rows]

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def close(self) -> None:
        """Close the underlying SQLite connection."""
        try:
            self._conn.close()
        except Exception:
            pass
